#!/usr/bin/env python3
"""Regenerate native/decomp/shim/decomp_cmd_bits.h from the decompilation.

The console reads each subaction command word big-endian, and MWCC allocates a
bit-field group from the *most* significant bit of its storage unit.  GCC can
be told both at once with `scalar_storage_order("big-endian")`; Clang ignores
that attribute in silence, which is P-502's gate zero.  This script restates
the same layout with no attribute at all: each struct over one 32-bit word in
host order, fields reversed and padded to the top, read through `CMD_U` (which
byte-swaps).  See the generated header for the full argument.

Run it after any change to the `struct CMD_BE` declarations in
<melee/lb/types.h>.  `ctest bit_order` fails if the two ever drift.

    native/tools/gen_cmd_bits.py            # rewrite both generated files
    native/tools/gen_cmd_bits.py --check    # exit 1 if either is out of date

It writes two files: the header the port compiles against, and the field table
`ctest bit_order` walks so that every field is checked rather than a sample.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'decomp', 'src', 'melee', 'lb', 'types.h')
OUT = os.path.join(ROOT, 'native', 'decomp', 'shim', 'decomp_cmd_bits.h')
CHECKS = os.path.join(ROOT, 'native', 'tests', 'cmd_bits_checks.inc')

WIDTH = {'u8': 8, 's8': 8, 'u16': 16, 's16': 16,
         'u32': 32, 's32': 32, 'int': 32, 'unsigned': 32}
SIGNED = {'u8': 0, 's8': 1, 'u16': 0, 's16': 1,
          'u32': 0, 's32': 1, 'int': 1, 'unsigned': 0}
BASE = '|'.join(WIDTH)


def parse(text):
    """Every `struct CMD_BE <name> { ... };` in declaration order."""
    out = []
    for m in re.finditer(r'struct CMD_BE (\w+) \{(.*?)\n\};', text, re.S):
        name, body = m.group(1), m.group(2)
        fields = []
        for line in body.split('\n'):
            line = re.sub(r'///.*$', '', line)
            line = re.sub(r'/\*.*?\*/', '', line).strip()
            if not line:
                continue
            mm = re.match(r'^(%s)\s+(\w+)\s*:\s*(\d+)\s*;$' % BASE, line)
            if mm:
                fields.append((mm.group(1), mm.group(2), int(mm.group(3))))
                continue
            mm = re.match(r'^(%s)\s+(\w+)\s*;$' % BASE, line)
            if mm:
                fields.append((mm.group(1), mm.group(2), None))
                continue
            sys.exit('gen_cmd_bits: cannot parse %s: %r' % (name, line))
        out.append((name, fields))
    return out


def layout(name, fields):
    """Where the console puts each field, as bits below the top of the word.

    MWCC fills a storage unit from its most significant bit and starts a new
    unit when the next field does not fit in what is left.
    """
    unit = used = 0
    unit_w = None
    placed = []
    for typ, fname, bits in fields:
        w = WIDTH[typ]
        if unit_w is None:
            unit_w = w
        if bits is None:                       # plain scalar member
            if used:
                unit, used = unit + 1, 0
            placed.append((fname, unit * unit_w, w, SIGNED[typ], True))
            unit, used = unit + 1, 0
            continue
        if w != unit_w:
            sys.exit('gen_cmd_bits: %s mixes %d- and %d-bit storage units'
                     % (name, unit_w, w))
        if used + bits > w:
            unit, used = unit + 1, 0
        placed.append((fname, unit * w + used, bits, SIGNED[typ], False))
        used += bits
    span = unit * (unit_w or 32) + used
    if span > 32:
        sys.exit('gen_cmd_bits: %s spans %d bits; CmdUnion is one word'
                 % (name, span))
    return placed


def declare(name, placed):
    if len(placed) == 1 and placed[0][4] and placed[0][2] == 32:
        fname, _, _, signed, _ = placed[0]
        return 'struct %s {\n    %s %s;\n};' % (name,
                                                's32' if signed else 'u32',
                                                fname)
    lines = ['struct %s {' % name]
    pos = 0
    for fname, p, n, signed, _ in sorted(placed, key=lambda f: -f[1]):
        shift = 32 - p - n
        if shift > pos:
            lines.append('    u32 : %d;' % (shift - pos))
            pos = shift
        lines.append('    %s %s : %d;' % ('s32' if signed else 'u32', fname, n))
        pos += n
    if pos < 32:
        lines.append('    u32 : %d;' % (32 - pos))
    lines.append('};')
    return '\n'.join(lines)


PREAMBLE = '''/*
 * Subaction / animation command bit-fields, laid out for a little-endian host.
 *
 * GENERATED by native/tools/gen_cmd_bits.py from the `struct CMD_BE`
 * declarations in <melee/lb/types.h>.  Do not edit by hand.
 *
 * The console reads each command word big-endian, and MWCC allocates a
 * bit-field group from the **most** significant bit of its storage unit.  GCC
 * can be told both at once with `scalar_storage_order("big-endian")`, which is
 * what `CMD_BE` expanded to.  **Clang ignores that attribute in silence**
 * (ADR-0022; the warning is -Wunknown-attributes, which the port's -w hides),
 * so the WebAssembly build decoded a real "play sound" word as opcode 4
 * instead of 17 and compiled without a complaint.  That is P-502's gate zero.
 *
 * So state the layout instead, with no attribute, in a form every compiler
 * agrees on: each struct covers one 32-bit word in **host** order with the
 * console's fields reversed and padded to the top, and the word is byte-
 * swapped where it is read -- `CMD_U` in <melee/lb/types.h>.  A field of width
 * `w` that the console puts `p` bits below the top of the word is declared
 * here above `32 - p - w` bits of padding and lower fields, signed exactly as
 * the console declares it.  Reversing alone is not enough and neither is
 * swapping alone; the pair is (G-180, and the W0 note's disproof).
 *
 * **The stream itself is never converted, and must not be.**  A subaction
 * script is not a uniform array of swappable words: `Command_05` (Subroutine)
 * and `Command_07` (Goto) carry a relocated **host pointer** inline
 * (lbcommand.c), so byte-swapping every word of a script at load -- the route
 * the P-502/W0 handoff proposed -- corrupts both.  The converter cannot find
 * the scripts either, which is the G-178 failure mode exactly.
 *
 * Proof: `ctest bit_order` decodes every field of every struct here and
 * compares it against the console's arithmetic, on both GCC and Emscripten.
 */
#ifndef MELEE_DECOMP_CMD_BITS_H
#define MELEE_DECOMP_CMD_BITS_H

/* Included from inside <melee/lb/types.h>; it supplies u32/s32. */

'''


def render():
    structs = parse(open(SRC, encoding='utf-8').read())
    if not structs:
        sys.exit('gen_cmd_bits: no `struct CMD_BE` declarations in %s' % SRC)
    body = '\n'.join(declare(n, layout(n, f)) for n, f in structs)
    return PREAMBLE + body + '\n\n#endif /* MELEE_DECOMP_CMD_BITS_H */\n'


def render_checks():
    """One CHK line per field: the console's bit position, width and sign."""
    structs = parse(open(SRC, encoding='utf-8').read())
    lines = ['/* GENERATED by native/tools/gen_cmd_bits.py -- do not edit.',
             ' *',
             ' * CHK(struct, field, bits-below-the-top-of-the-word, width,',
             ' * is-signed): what the console reads out of a command word.  The',
             ' * test reads the same field through the port\'s declaration and',
             ' * compares.  Every field of every CMD_BE struct is here. */']
    for name, fields in structs:
        for fname, p, n, signed, _plain in layout(name, fields):
            lines.append('CHK(%s, %s, %d, %d, %d);' % (name, fname, p, n, signed))
    return '\n'.join(lines) + '\n'


def write(path, text, check):
    cur = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
    if check:
        if cur != text:
            sys.exit('%s is out of date; run native/tools/gen_cmd_bits.py'
                     % os.path.relpath(path, ROOT))
        return
    open(path, 'w', encoding='utf-8').write(text)
    print('wrote %s' % os.path.relpath(path, ROOT))


if __name__ == '__main__':
    check = '--check' in sys.argv
    write(OUT, render(), check)
    write(CHECKS, render_checks(), check)
    if check:
        print('decomp_cmd_bits.h, cmd_bits_checks.inc: up to date')
